"""empty message

Revision ID: 215f7739ca2a
Revises: 
Create Date: 2020-01-28 15:03:21.873802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215f7739ca2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TA',
    sa.Column('TA_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('Dept', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('TA_id')
    )
    with op.batch_alter_table('TA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_TA_Dept'), ['Dept'], unique=False)
        batch_op.create_index(batch_op.f('ix_TA_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_TA_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_TA_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_TA_username'), ['username'], unique=True)

    op.create_table('attendance',
    sa.Column('Attd_ID', sa.Integer(), nullable=False),
    sa.Column('Present', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Attd_ID')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_timestamp'), ['timestamp'], unique=False)

    op.create_table('course',
    sa.Column('Course_ID', sa.Integer(), nullable=False),
    sa.Column('Course_name', sa.String(length=64), nullable=True),
    sa.Column('Classes_held', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Course_ID')
    )
    op.create_table('prof',
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('Dept', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('prof_id')
    )
    with op.batch_alter_table('prof', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prof_Dept'), ['Dept'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_prof_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_prof_username'), ['username'], unique=True)

    op.create_table('student',
    sa.Column('stud_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('Dept', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('stud_id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_Dept'), ['Dept'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_year'), ['year'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_lname'))
        batch_op.drop_index(batch_op.f('ix_user_fname'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_year'))
        batch_op.drop_index(batch_op.f('ix_student_username'))
        batch_op.drop_index(batch_op.f('ix_student_lname'))
        batch_op.drop_index(batch_op.f('ix_student_fname'))
        batch_op.drop_index(batch_op.f('ix_student_email'))
        batch_op.drop_index(batch_op.f('ix_student_Dept'))

    op.drop_table('student')
    with op.batch_alter_table('prof', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prof_username'))
        batch_op.drop_index(batch_op.f('ix_prof_lname'))
        batch_op.drop_index(batch_op.f('ix_prof_fname'))
        batch_op.drop_index(batch_op.f('ix_prof_email'))
        batch_op.drop_index(batch_op.f('ix_prof_Dept'))

    op.drop_table('prof')
    op.drop_table('course')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_timestamp'))

    op.drop_table('attendance')
    with op.batch_alter_table('TA', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TA_username'))
        batch_op.drop_index(batch_op.f('ix_TA_lname'))
        batch_op.drop_index(batch_op.f('ix_TA_fname'))
        batch_op.drop_index(batch_op.f('ix_TA_email'))
        batch_op.drop_index(batch_op.f('ix_TA_Dept'))

    op.drop_table('TA')
    # ### end Alembic commands ###
