"""empty message

Revision ID: 9327945a10ef
Revises: cbc11f2555c9
Create Date: 2020-03-12 11:25:39.855554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9327945a10ef'
down_revision = 'cbc11f2555c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'Classes_held')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('Classes_held', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
