"""empty message

Revision ID: 937590d87f32
Revises: 
Create Date: 2020-01-21 12:48:54.837822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937590d87f32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TA',
    sa.Column('TA_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('Dept', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('TA_id')
    )
    op.create_index(op.f('ix_TA_Dept'), 'TA', ['Dept'], unique=False)
    op.create_index(op.f('ix_TA_email'), 'TA', ['email'], unique=True)
    op.create_index(op.f('ix_TA_fname'), 'TA', ['fname'], unique=False)
    op.create_index(op.f('ix_TA_lname'), 'TA', ['lname'], unique=False)
    op.create_index(op.f('ix_TA_username'), 'TA', ['username'], unique=True)
    op.create_table('courses',
    sa.Column('Course_ID', sa.Integer(), nullable=False),
    sa.Column('Course_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Course_ID')
    )
    op.create_table('prof',
    sa.Column('prof_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('Dept', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('prof_id')
    )
    op.create_index(op.f('ix_prof_Dept'), 'prof', ['Dept'], unique=False)
    op.create_index(op.f('ix_prof_email'), 'prof', ['email'], unique=True)
    op.create_index(op.f('ix_prof_fname'), 'prof', ['fname'], unique=False)
    op.create_index(op.f('ix_prof_lname'), 'prof', ['lname'], unique=False)
    op.create_index(op.f('ix_prof_username'), 'prof', ['username'], unique=True)
    op.create_table('student',
    sa.Column('stud_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('Dept', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('stud_id')
    )
    op.create_index(op.f('ix_student_Dept'), 'student', ['Dept'], unique=False)
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_fname'), 'student', ['fname'], unique=False)
    op.create_index(op.f('ix_student_lname'), 'student', ['lname'], unique=False)
    op.create_index(op.f('ix_student_username'), 'student', ['username'], unique=True)
    op.create_index(op.f('ix_student_year'), 'student', ['year'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_fname'), 'user', ['fname'], unique=False)
    op.create_index(op.f('ix_user_lname'), 'user', ['lname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_lname'), table_name='user')
    op.drop_index(op.f('ix_user_fname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_student_year'), table_name='student')
    op.drop_index(op.f('ix_student_username'), table_name='student')
    op.drop_index(op.f('ix_student_lname'), table_name='student')
    op.drop_index(op.f('ix_student_fname'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_index(op.f('ix_student_Dept'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_prof_username'), table_name='prof')
    op.drop_index(op.f('ix_prof_lname'), table_name='prof')
    op.drop_index(op.f('ix_prof_fname'), table_name='prof')
    op.drop_index(op.f('ix_prof_email'), table_name='prof')
    op.drop_index(op.f('ix_prof_Dept'), table_name='prof')
    op.drop_table('prof')
    op.drop_table('courses')
    op.drop_index(op.f('ix_TA_username'), table_name='TA')
    op.drop_index(op.f('ix_TA_lname'), table_name='TA')
    op.drop_index(op.f('ix_TA_fname'), table_name='TA')
    op.drop_index(op.f('ix_TA_email'), table_name='TA')
    op.drop_index(op.f('ix_TA_Dept'), table_name='TA')
    op.drop_table('TA')
    # ### end Alembic commands ###
