"""empty message

Revision ID: ad6d7e1ff25c
Revises: 
Create Date: 2020-06-29 10:49:50.007562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6d7e1ff25c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('ID', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('role',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_default'), ['default'], unique=False)

    op.create_table('course',
    sa.Column('ID', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('classes_held', sa.Integer(), nullable=True),
    sa.Column('dept_ID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['dept_ID'], ['department.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('dept', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept'], ['department.ID'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    op.create_table('prof_courses',
    sa.Column('FID', sa.String(length=64), nullable=False),
    sa.Column('CID', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['CID'], ['course.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['FID'], ['user.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('FID', 'CID')
    )
    op.create_table('stud_courses',
    sa.Column('SID', sa.String(length=64), nullable=False),
    sa.Column('CID', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['CID'], ['course.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SID'], ['user.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SID', 'CID')
    )
    op.create_table('ta_courses',
    sa.Column('TAID', sa.String(length=64), nullable=False),
    sa.Column('CID', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['CID'], ['course.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TAID'], ['user.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TAID', 'CID')
    )
    op.create_table('attendance',
    sa.Column('CID', sa.String(length=64), nullable=False),
    sa.Column('SID', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('FID', sa.String(length=64), nullable=True),
    sa.Column('TAID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['CID'], ['stud_courses.CID'], ),
    sa.ForeignKeyConstraint(['FID'], ['prof_courses.FID'], ),
    sa.ForeignKeyConstraint(['SID'], ['stud_courses.SID'], ),
    sa.ForeignKeyConstraint(['TAID'], ['ta_courses.TAID'], ),
    sa.PrimaryKeyConstraint('CID', 'SID', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('ta_courses')
    op.drop_table('stud_courses')
    op.drop_table('prof_courses')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_lname'))
        batch_op.drop_index(batch_op.f('ix_user_fname'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('course')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_default'))

    op.drop_table('role')
    op.drop_table('department')
    # ### end Alembic commands ###
