"""empty message

Revision ID: b6eb75a969f0
Revises: 
Create Date: 2020-03-11 13:44:07.153549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6eb75a969f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('Course_ID', sa.Integer(), nullable=False),
    sa.Column('Stud_ID', sa.Integer(), nullable=False),
    sa.Column('Present', sa.String(length=4), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('Faculty', sa.Integer(), nullable=True),
    sa.Column('TA', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Course_ID'], ['stud_courses.course_id'], ),
    sa.ForeignKeyConstraint(['Faculty'], ['prof_courses.prof_id'], ),
    sa.ForeignKeyConstraint(['Stud_ID'], ['stud_courses.stud_id'], ),
    sa.ForeignKeyConstraint(['TA'], ['ta_courses.ta_id'], ),
    sa.PrimaryKeyConstraint('Course_ID', 'Stud_ID', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
