"""empty message

Revision ID: bc9251478ca5
Revises: 937590d87f32
Create Date: 2020-01-23 12:28:02.382627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9251478ca5'
down_revision = '937590d87f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('Course_ID', sa.Integer(), nullable=False),
    sa.Column('Course_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Course_ID')
    )
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('Course_ID', sa.INTEGER(), nullable=False),
    sa.Column('Course_name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Course_ID')
    )
    op.drop_table('course')
    # ### end Alembic commands ###
