"""empty message

Revision ID: cb16c9d13ee2
Revises: 6d0e583a60ad
Create Date: 2020-03-05 12:10:20.574177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb16c9d13ee2'
down_revision = '6d0e583a60ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_timestamp')
        batch_op.drop_column('Attd_ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Attd_ID', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_attendance_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
